### ISSUE TITLE
Service Provider > Dashboard > Video Consultation > The endpoint for receiving Scheduled appointment ( from patient end is missing )

### ISSUE THREAD

**Issue by Arushiv13** [Arushiv13/Lyfboat-#1]

**Comment by vishakhagurjarvayuz** [comment]
![Screenshot_1637742982](https://user-images.githubusercontent.com/88379134/143205047-d118261a-702d-442e-8db1-e83dfdb17fb0.png)

**Comment by abhineetv** [comment]
What do you mean by "from patient end is missing"? Patient name?
If It is patient name then it is added now.

**Comment by Arushiv13** [comment]
@abhineetv  - The endpoint for receiving Scheduled appointment ( from patient's side is missing ). The endpoint where you're are approving the VideoConsultation and forwarding it to the service providers is missing. @anuj@lyfboat.com

**Comment by anuj-gupta-lyfboat** [comment]
@abhineetv can you comment? As far as I recall the list of Video Consultations is supposed to be sent for each member at the time of fetching the inquiries. No separate endpoint is required. Approving VC is a manual setup of a Google meet and NO forwarding to service providers is happening either.

**Comment by abhineetv** [comment]
I think we've informed this earlier too that VC approval happens at the backend. App is only responsible to request VC, for this we already have one API.

Then we also have another API to get VCs i.e. Get VIdeo Consultations. This works for both patients and providers.

**Comment by vishakhagurjarvayuz** [comment]
we are using this 
https://react.lyfboat.com/api/member/consultations?user_id=22618&token=dcb98b531d2a02179d7bcedd5122f81d

**Comment by vishakhagurjarvayuz** [comment]
![videoconsultationAll](https://user-images.githubusercontent.com/88379134/145517022-1c83d7cb-8fe1-470c-b564-5d737670b615.png)
using this endpoint https://react.lyfboat.com/api/consultations?user_id=2&token=d931e48a2225a61cca3f204a3d7bc5c5
