### ISSUE TITLE
Patient>Medical Provider chatList

### ISSUE THREAD

**Issue by vishakhagurjarvayuz** [Arushiv13/Lyfboat-#10]
![medical_provider](https://user-images.githubusercontent.com/88379134/144357897-0fb4c0ea-a7fd-42e4-87ec-8a2201f06426.png)

**Comment by Arushiv13** [comment]
@vishakhagurjarvayuz  use parent inquiry id here

**Comment by Arushiv13** [comment]
@abhineet@lyfboat.com , still not working

**Comment by abhineetv** [comment]
Can you pls help me understand what is not working here?

- https://react.lyfboat.com/api/conversation/list/by-member?token=787595a3f2c727cbd7766cb12a4c1397&user_id= 22618
- https://react.lyfboat.com/api/conversation/byInquiry/47938?token=787595a3f2c727cbd7766cb12a4c1397&user_id= 22618

Both endpoints seems to be working to me.
