### ISSUE TITLE
Every Screen > Give space before Header, it is fetting conjusted with the phone header deatisl , alos attaching a screenshot > the back button is not aligned with the text below

### ISSUE THREAD

**Issue by Arushiv13** [Arushiv13/Lyfboat-#130]
![WhatsApp Image 2022-04-29 at 12 15 54 PM](https://user-images.githubusercontent.com/94099426/165897736-4e0fa1e2-3f15-45df-9033-91aecdd2e47d.jpeg)

**Comment by Arushiv13** [comment]
Still the same space is there @Ahlam000

**Comment by Ahlam000** [comment]
![Screenshot_1653480141](https://user-images.githubusercontent.com/101115620/170257580-8ca71e37-b1db-46e5-80b0-8ab37eb49ad5.png)
please check if this much space is enough

**Comment by Ahlam000** [comment]
![WhatsApp Image 2022-05-25 at 5 35 44 PM](https://user-images.githubusercontent.com/101115620/170258079-779c6b34-2dce-47dc-bbab-4d07f31a3f84.jpeg)
from real device
