### ISSUE TITLE
Profile > Edit profile is not workinh > Profile image, Nmae , Age is not getting editted 

### ISSUE THREAD

**Issue by Arushiv13** [Arushiv13/Lyfboat-#135]

**Comment by Arushiv13** [comment]
Edit Profile :

1. Keep only Year Calendar from 1940 - 2018
2. Age and Country are not coming as it was entered while Signing up

**Comment by Arushiv13** [comment]
Edit Profile - Done ( Tick icon) option is not working

**Comment by Ahlam000** [comment]
@Arushiv13  which login credentials you are using
and age is not coming from api we are calculating it manually from front end
