### ISSUE TITLE
Profile > camera overlay is on align with the profile image on edit profile

### ISSUE THREAD

**Issue by manojnegi07** [Arushiv13/Lyfboat-#211]
![image](https://user-images.githubusercontent.com/92147060/180986869-88d85101-7758-4960-9596-e202a2f6b717.png)

**Comment by Arushiv13** [comment]
It's same. Not changed @Ahlam000

**Comment by Arushiv13** [comment]
![MicrosoftTeams-image (208)](https://user-images.githubusercontent.com/94099426/195549568-dc5206a1-d129-4b3a-a938-bf56b756bd32.png)
@Ahlam000  still not done.
