### ISSUE TITLE
Clearly untested. Profile still blank.

### ISSUE THREAD

**Issue by Arushiv13** [Arushiv13/Lyfboat-#369]
https://drive.google.com/file/d/116Mgr29dz8ZB2UBPGbxrHifY2cs9l8VJ/view?usp=sharing

**Comment by Ahlam000** [comment]
![Screenshot_1665568979](https://user-images.githubusercontent.com/101115620/195314037-5c68f2ad-a09a-49ea-bd6c-3dc0e930e87f.png)
@Arushiv13  its working already
