### ISSUE TITLE
Status text change from "responded quotations" to "responded" and "pending quotations" tp "pending". Filters dropdown to match the labels.

### ISSUE THREAD

**Issue by Arushiv13** [Arushiv13/Lyfboat-#383]
https://drive.google.com/file/d/11NKvml6yADYfcTMFyDj2PJoMAFyieEkJ/view?usp=sharing

**Comment by Ahlam000** [comment]
@Arushiv13  need clarity first it was changed to responded quotations now again need to change to responded only

**Comment by Arushiv13** [comment]
Keep this one only this time - Responded and Pending everywhere we are using Filters

**Comment by Ahlam000** [comment]
@Arushiv13  please confirm from client whther in member module we can keeo recieved and pending only
