### ISSUE TITLE
Everwhere we are using Treatment name with Ref Id, here we are using Inquiry ID? Needs to be consistent in all modules

### ISSUE THREAD

**Issue by Arushiv13** [Arushiv13/Lyfboat-#384]
https://drive.google.com/file/d/11Ts1oQzfr0d8GQ0plqqQrhPNQ5duivhh/view?usp=sharing

**Comment by Ahlam000** [comment]
@Arushiv13  we are using inquiry id in chats

**Comment by Arushiv13** [comment]
@Ahlam000 pls add Ref ID in the Chat.
