### ISSUE TITLE
Placeholder text in grey in input boxes is too large. Also change label "comments" to "Other Remarks"  and the box is too small as  paragraph text will be provided here not one liners. 

### ISSUE THREAD

**Issue by Arushiv13** [Arushiv13/Lyfboat-#387]
https://drive.google.com/file/d/11XPJzNZ10ZEebWaN3rTffcs9UbmwKEKv/view?usp=sharing

**Comment by Ahlam000** [comment]
@Arushiv13  input box is expanded when its focused if we give more height to box then modal will expand
