### ISSUE TITLE
Service Provider>Medical inquiries > Inquiry Details

### ISSUE THREAD

**Issue by vishakhagurjarvayuz** [Arushiv13/Lyfboat-#4]
![inquirydetails](https://user-images.githubusercontent.com/88379134/143209938-88f7fc27-f0ba-46e1-9303-0c34d802f81a.png)

**Comment by Arushiv13** [comment]
@vishakhagurjarvayuz  Please mention the account and description for the issue

**Comment by vishakhagurjarvayuz** [comment]
account - medanta@lyfboat.com
We are not getting inquiry details while using this endpoint
https://react.lyfboat.com/api/appinquiry/47957?token=7a7a4345504e3623e640c6f330cef00a&user_id=2

**Comment by abhineetv** [comment]
Fixed.
