### ISSUE TITLE
Chat>Assistance>Last chat timing

### ISSUE THREAD

**Issue by vishakhagurjarvayuz** [Arushiv13/Lyfboat-#6]
![chatTiming](https://user-images.githubusercontent.com/88379134/143234402-acebd33d-76ba-4e5f-9863-5a7840ac8282.png)
In this https://react.lyfboat.com/api/inquiries?token=9155adc8de2e22a3315c13f04dda264f&user_id=22618&length=10&start=0&sort=inquiry_id&order=desc we need last_message timing.

**Comment by abhineetv** [comment]
Use `https://react.lyfboat.com/api/conversation/list/by-member` endpoint. Inquiries endpoint is not meant for chat list.
