### ISSUE TITLE
Service Provider>Inquiry Details>Provide Opinion

### ISSUE THREAD

**Issue by vishakhagurjarvayuz** [Arushiv13/Lyfboat-#8]
![Screenshot_1637904420](https://user-images.githubusercontent.com/88379134/143531457-c9e493ac-727b-4bd0-815d-7372c9b8470a.png)
We need currency   in this  https://react.lyfboat.com/api/countries/withCountryCode

**Comment by abhineetv** [comment]
We do not support all currencies. Lets confirm this with anuj once in the meeting. Most likely this is going to be "Dollor", "Euro" & "INR" only. No need for an API for now.

**Comment by anuj-gupta-lyfboat** [comment]
That is correct we do not support all currencies so API is not required. Opinion can be provided in $ or INR, we will anyway convert to USD from backend when sending the quotation.
