### ISSUE TITLE
Doctor>Doctor Profile

### ISSUE THREAD

**Issue by vishakhagurjarvayuz** [Arushiv13/Lyfboat-#9]
![doctorprofile](https://user-images.githubusercontent.com/88379134/143532554-d7f7c89e-1025-4bb6-bbe6-225e9e34ec73.png)
We are not getting email and phone number in this https://react.lyfboat.com/api/doctor/profile/id/12

**Comment by abhineetv** [comment]
Let's get it confirmed from Anuj.
